In [3]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import os
from mpl_toolkits.axes_grid1 import ImageGrid

def comparison_grid(
    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/backpack/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/backpack/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/backpack/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/backpack/',
    ):

    titles = ["Noise Conv", "Mask", "Original", "Train Data"]  # Titles for each image
    noise_conv_augmented = [f'{noise_conv_augmented_path}{file}' for file in sorted(os.listdir(noise_conv_augmented_path))]
    mask_augmented = [f'{mask_augmented_path}{file}' for file in sorted(os.listdir(mask_augmented_path))]
    original_augmented = [f'{original_augmented_path}{file}' for file in sorted(os.listdir(original_augmented_path))]
    train_data = [f'{train_data_path}{file}' for file in sorted(os.listdir(train_data_path))]
    
    print(len(noise_conv_augmented), len(mask_augmented), len(original_augmented), len(train_data))

    for i in range(len(noise_conv_augmented)):
        fig = plt.figure(figsize=(16, 8))
        grid = ImageGrid(fig, 111,
            nrows_ncols=(1, 4),  # Creates 1 row, 4 columns
            axes_pad=0.3,  # Pad between Axes in inches
        )

        im1 = Image.open(noise_conv_augmented[i])
        im2 = Image.open(mask_augmented[i])
        im3 = Image.open(original_augmented[i])
        im4 = Image.open(train_data[i])

        images = [im1, im2, im3, im4]  # Store images in a list

        for ax, im, title in zip(grid, images, titles):
            ax.imshow(im)
            ax.set_title(title, fontsize=14)  # Set the title for each subplot
            ax.axis("off")  # Hide axes for better visualization

        plt.show()
        
comparison_grid(
    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/backpack/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/backpack/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/backpack/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/backpack/'
)

In [7]:
comparison_grid(
    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/candle/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/candle/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/candle/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/candle/'
)

In [6]:
comparison_grid(
    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/clock/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/clock/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/clock/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/clock/'
)

In [ ]:
comparison_grid(
    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/cat/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/cat/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/cat/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/cat/'
)

In [ ]:
comparison_grid(
    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/colorful_sneaker/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/colorful_sneaker/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/colorful_sneaker/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/colorful_sneaker/'
)

In [4]:
comparison_grid(
    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog_data/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog_data/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog_data/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/dog_data/'
)

In [ ]:
comparison_grid(
    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog2/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog2/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog2/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/dog2/'
)

In [ ]:
comparison_grid(
    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog3/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog3/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog3/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/dog3/'
)

In [ ]:
comparison_grid(
    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/teapot/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/teapot/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/teapot/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/teapot/'
)

In [ ]:
comparison_grid(
    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/vase/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/vase/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/vase/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/vase/'
)

In [1]:
import clip

model, preprocess = clip.load("ViT-B/32", device='cuda')

In [2]:
import os
from PIL import Image
import torch
from scipy.stats import wasserstein_distance, wasserstein_distance_nd
from tqdm import tqdm

def compare_image_embeds(
    noise_conv_augmented_path,
    mask_augmented_path,
    original_augmented_path,
    train_data_path,
    model=model, 
    preprocess=preprocess, 
    device='cuda'
):
    if model is None or preprocess is None:
        raise ValueError("Model and preprocess function must be provided")

    noise_conv_embeds = []
    mask_embeds = []
    orig_embeds = []
    train_embeds = []
    
    for img_name in tqdm(os.listdir(noise_conv_augmented_path), desc="Processing noise_conv images"):
        img = Image.open(os.path.join(noise_conv_augmented_path, img_name))
        img_emb = model.encode_image(preprocess(img).unsqueeze(0).to(device))
        noise_conv_embeds.append(img_emb.detach().cpu())  # Fixed

    for img_name in tqdm(os.listdir(mask_augmented_path), desc="Processing mask images"):
        img = Image.open(os.path.join(mask_augmented_path, img_name))
        img_emb = model.encode_image(preprocess(img).unsqueeze(0).to(device))
        mask_embeds.append(img_emb.detach().cpu())  # Fixed

    for img_name in tqdm(os.listdir(original_augmented_path), desc="Processing original images"):
        img = Image.open(os.path.join(original_augmented_path, img_name))
        img_emb = model.encode_image(preprocess(img).unsqueeze(0).to(device))
        orig_embeds.append(img_emb.detach().cpu())  # Fixed

    for img_name in tqdm(os.listdir(train_data_path), desc="Processing train images"):
        img = Image.open(os.path.join(train_data_path, img_name))
        img_emb = model.encode_image(preprocess(img).unsqueeze(0).to(device))
        train_embeds.append(img_emb.detach().cpu())  # Fixed

    # Ensure tensors are stacked correctly
    noise_conv_embeds = torch.stack(noise_conv_embeds)
    mask_embeds = torch.stack(mask_embeds)
    orig_embeds = torch.stack(orig_embeds)
    train_embeds = torch.stack(train_embeds)
    
    train_embeds = train_embeds.squeeze(1)        # was (6,1,768), becomes (6,768)
    noise_conv_embeds = noise_conv_embeds.squeeze(1)
    mask_embeds = mask_embeds.squeeze(1)
    orig_embeds = orig_embeds.squeeze(1)

    
    print(noise_conv_embeds)
    # Compute Wasserstein distances
    noise_conv_train = wasserstein_distance_nd(train_embeds.numpy(), noise_conv_embeds.numpy())
    mask_train = wasserstein_distance_nd(train_embeds.numpy(), mask_embeds.numpy())
    orig_train = wasserstein_distance_nd(train_embeds.numpy(), orig_embeds.numpy())

    print(f'distance between noise_conv and train data : {noise_conv_train}, distance between mask and train data : {mask_train}, distance between orig dreambooth and train data : {orig_train}')


In [3]:
compare_image_embeds(

    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/backpack/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/backpack/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/backpack/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/backpack/'
)


Processing train images: 100%|██████████| 6/6 [00:00<00:00, 20.36it/s]


tensor([[-0.0492,  0.2352,  0.2517,  ...,  0.1484, -0.4138,  0.3000],
        [ 0.0481,  0.3728,  0.0120,  ...,  0.1597, -0.1814, -0.0070],
        [ 0.1653,  0.5352,  0.0043,  ...,  0.2018, -0.2399, -0.0677],
        [-0.0395,  0.6665,  0.1575,  ..., -0.0351, -0.3289, -0.0373],
        [-0.1361,  0.4922, -0.0010,  ...,  0.1742, -0.3669,  0.1549],
        [ 0.0323,  0.5220,  0.0292,  ...,  0.0247, -0.0648, -0.1471]],
       dtype=torch.float16)
distance between noise_conv and train data : 5.422525166600748, distance between mask and train data : 5.190588970844959, distance between orig dreambooth and train data : 5.659513114773426


In [4]:
compare_image_embeds(

    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/backpack_dog/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/backpack_dog/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/backpack_dog/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/backpack_dog/'
)

Processing train images: 100%|██████████| 5/5 [00:00<00:00, 10.05it/s]

tensor([[ 0.0485,  0.1002,  0.1814,  ...,  0.1432, -0.4604,  0.2576],
        [ 0.3188,  0.3252, -0.2074,  ..., -0.1685, -0.0271, -0.1335],
        [-0.2062,  0.1270,  0.1340,  ..., -0.0497, -0.2404, -0.0219],
        [ 0.0473,  0.2676, -0.2625,  ...,  0.3562, -0.1370,  0.1158],
        [ 0.0271,  0.1256,  0.0828,  ..., -0.0698, -0.1610,  0.5854]],
       dtype=torch.float16)
distance between noise_conv and train data : 8.168058760352741, distance between mask and train data : 7.428080172948528, distance between orig dreambooth and train data : 7.15294789309725


In [5]:
compare_image_embeds(

    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/candle/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/candle/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/candle/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/candle/'
)

Processing train images: 100%|██████████| 5/5 [00:00<00:00,  7.12it/s]

tensor([[-0.2496,  0.0690,  0.2712,  ...,  0.2297, -0.0436, -0.1190],
        [-0.3103,  0.0586,  0.3320,  ...,  0.1890,  0.1564,  0.2084],
        [-0.3674,  0.0209,  0.2544,  ...,  0.3608,  0.1235,  0.2468],
        [-0.2695, -0.1940, -0.0052,  ...,  0.2190,  0.0642, -0.0428],
        [-0.3335, -0.1791,  0.1537,  ...,  0.4163,  0.2112,  0.0400]],
       dtype=torch.float16)
distance between noise_conv and train data : 8.260203430739429, distance between mask and train data : 7.25416150471224, distance between orig dreambooth and train data : 7.151987293451321


In [6]:
compare_image_embeds(

    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/cat/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/cat/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/cat/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/cat/'
)

Processing train images: 100%|██████████| 5/5 [00:00<00:00, 20.30it/s]

tensor([[-0.3787,  0.1713,  0.2847,  ...,  0.6606, -0.1177, -0.3037],
        [-0.1675,  0.1287,  0.3542,  ...,  0.3936,  0.0481, -0.2214],
        [-0.1321,  0.0607,  0.2783,  ...,  0.2179, -0.0580, -0.0872],
        [-0.0071, -0.1566,  0.1608,  ...,  0.5342, -0.1458,  0.0470],
        [-0.1667,  0.0071,  0.2485,  ...,  0.6401, -0.0897, -0.2451]],
       dtype=torch.float16)
distance between noise_conv and train data : 4.084605939897933, distance between mask and train data : 3.8363398822721693, distance between orig dreambooth and train data : 3.8333657693737018


In [7]:
compare_image_embeds(

    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/clock/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/clock/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/clock/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/clock/'
)

Processing train images: 100%|██████████| 6/6 [00:00<00:00, 14.87it/s]

tensor([[ 0.2104,  0.0364, -0.1140,  ...,  0.5605, -0.0102,  0.2388],
        [ 0.2002, -0.0634, -0.2705,  ...,  0.5845,  0.0249,  0.2186],
        [ 0.2233, -0.0782, -0.2893,  ...,  0.8311, -0.1056, -0.0104],
        [ 0.1787,  0.2913, -0.2585,  ...,  0.3167, -0.0622,  0.1938],
        [ 0.1962, -0.0182, -0.2177,  ...,  0.5278,  0.0865, -0.0216],
        [ 0.1497,  0.1044, -0.1951,  ...,  0.4319, -0.2407,  0.0247]],
       dtype=torch.float16)
distance between noise_conv and train data : 5.891908305708153, distance between mask and train data : 5.602047164894623, distance between orig dreambooth and train data : 5.087403861110392


In [8]:
compare_image_embeds(

    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/colorful_sneaker/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/colorful_sneaker/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/colorful_sneaker/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/colorful_sneaker/'
)

Processing train images: 100%|██████████| 5/5 [00:00<00:00,  7.85it/s]

tensor([[-0.7344, -0.0427,  0.3933,  ..., -0.3684,  0.2559,  0.7080],
        [-0.6841, -0.0433,  0.2874,  ...,  0.0101, -0.0152,  0.7773],
        [-0.5513,  0.0436,  0.4504,  ..., -0.1003,  0.1686,  0.5854],
        [-0.4680, -0.0260,  0.3879,  ..., -0.0847,  0.2489,  0.5713],
        [-0.7456, -0.1243,  0.3203,  ..., -0.1539,  0.1337,  0.5244]],
       dtype=torch.float16)
distance between noise_conv and train data : 5.204299973406551, distance between mask and train data : 5.31989876510594, distance between orig dreambooth and train data : 5.44148438737909


In [9]:
compare_image_embeds(

    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog_data/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog_data/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog_data/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/dog_data/'
)

Processing train images: 100%|██████████| 5/5 [00:00<00:00,  5.50it/s]

tensor([[-0.1030,  0.3682, -0.0508,  ...,  0.4941, -0.2197, -0.0889],
        [-0.1215,  0.1979,  0.0604,  ...,  0.3982, -0.2474, -0.0775],
        [-0.0326,  0.2566, -0.0432,  ...,  0.3882, -0.1984, -0.1196],
        [-0.0214,  0.3037,  0.1014,  ...,  0.4514, -0.2100, -0.1973],
        [-0.0535,  0.4026, -0.0590,  ...,  0.3997, -0.2800, -0.0518]],
       dtype=torch.float16)
distance between noise_conv and train data : 3.409234934484566, distance between mask and train data : 4.093245945449982, distance between orig dreambooth and train data : 4.124167961837731


In [10]:
compare_image_embeds(

    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog2/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog2/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog2/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/dog2/'
)

Processing train images: 100%|██████████| 6/6 [00:00<00:00, 14.03it/s]

tensor([[ 0.1785,  0.0429,  0.0091,  ...,  0.4309,  0.2163, -0.3662],
        [ 0.2554,  0.1664, -0.0050,  ...,  0.2350,  0.3765, -0.2583],
        [ 0.1461,  0.2283,  0.1247,  ...,  0.5474,  0.2058, -0.1831],
        [-0.0155,  0.2249,  0.0861,  ...,  0.3867,  0.2422, -0.1137],
        [ 0.1382,  0.2089, -0.0856,  ...,  0.5049,  0.1624, -0.1219],
        [ 0.3140,  0.1554,  0.0413,  ...,  0.3865,  0.2788, -0.1672]],
       dtype=torch.float16)
distance between noise_conv and train data : 4.544684845961004, distance between mask and train data : 4.543222441615668, distance between orig dreambooth and train data : 4.675732601286677


In [11]:
compare_image_embeds(

    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog3/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog3/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/dog3/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/dog3/'
)

Processing train images: 100%|██████████| 6/6 [00:00<00:00, 21.64it/s]

tensor([[-0.0421, -0.4739, -0.1809,  ...,  0.2512,  0.1219,  0.1768],
        [ 0.0014, -0.2249, -0.1547,  ...,  0.2966, -0.1580,  0.0295],
        [ 0.3105, -0.0655,  0.1011,  ...,  0.3621,  0.3506,  0.3430],
        [-0.0016, -0.1791, -0.0551,  ...,  0.1416,  0.0411,  0.4504],
        [ 0.2014, -0.2030, -0.0798,  ...,  0.2445,  0.0390,  0.2390],
        [ 0.0580, -0.2698, -0.1422,  ...,  0.4636,  0.2822,  0.1583]],
       dtype=torch.float16)
distance between noise_conv and train data : 6.656507657089268, distance between mask and train data : 5.961517583448776, distance between orig dreambooth and train data : 6.199716276806934


In [12]:
compare_image_embeds(
    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/teapot/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/teapot/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/teapot/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/teapot/'
)

Processing train images: 100%|██████████| 5/5 [00:00<00:00, 21.89it/s]

tensor([[-0.0869,  0.6987,  0.1025,  ...,  0.1915, -0.5171, -0.5093],
        [ 0.1887,  0.5400, -0.0015,  ...,  0.3345, -0.3359, -0.4006],
        [ 0.1114,  0.5933,  0.1057,  ...,  0.2490, -0.4639, -0.3174],
        [-0.2642,  0.3599,  0.0418,  ...,  0.3628, -0.3743, -0.6045],
        [ 0.2607,  0.5195,  0.0082,  ...,  0.1066, -0.4517, -0.3301]],
       dtype=torch.float16)
distance between noise_conv and train data : 5.697302285103021, distance between mask and train data : 5.425620640038461, distance between orig dreambooth and train data : 5.470084692752099


In [14]:
compare_image_embeds(
    noise_conv_augmented_path = '/home/jupyter/aelif_augmentation/results_images/vase/aug/',
    mask_augmented_path = '/home/jupyter/aelif_augmentation/results_images/vase/aug-mask/',
    original_augmented_path = '/home/jupyter/aelif_augmentation/results_images/vase/original/',
    train_data_path = '/home/jupyter/aelif_augmentation/dreambooth/dataset/vase/'
)

Processing train images: 100%|██████████| 6/6 [00:00<00:00, 36.97it/s]

tensor([[-0.3154,  0.3669,  0.3733,  ...,  0.1754,  0.2532, -0.2974],
        [-0.2051,  0.5068,  0.2607,  ...,  0.4790, -0.0849, -0.0417],
        [ 0.2771,  0.4343,  0.0109,  ...,  0.2542,  0.3054,  0.1175],
        [-0.0194,  0.4666,  0.0081,  ...,  0.2900, -0.1204,  0.0194],
        [ 0.0922,  0.4399, -0.0030,  ...,  0.4585,  0.0147,  0.3040],
        [-0.1241,  0.4092,  0.0773,  ...,  0.3218,  0.0334,  0.1746]],
       dtype=torch.float16)
distance between noise_conv and train data : 5.261885310450992, distance between mask and train data : 4.807509642387186, distance between orig dreambooth and train data : 4.996196860592633
